mynotes_site/mynotes_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
]

mynotes_site/notes/urls.py
from django.urls import path

from .views import all_notes, create_note, delete_notes, add_subtask, add_subtask_for_id

app_name = 'notes'

urlpatterns = [
    path('', all_notes, name='all_notes'),
    path('create/', create_note, name='create_note'),
    path('delete/', delete_notes, name='delete_selected'),
    path('addsub/', add_subtask, name='add_subtask'),
    path('add_subtask_for_id/<int:note_id>/', add_subtask_for_id, name='add_subtask_for_id'),
]

mynotes_site/notes/models.py
from django.db import models


class Subtasks(models.Model):
    title = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    note = models.ForeignKey('Note', on_delete=models.CASCADE)


class Note(models.Model):
    title = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

mynotes_site/notes/forms.py
from django import forms


class NoteForm(forms.Form):
    title = forms.CharField()


class SubtasksForm(forms.Form):
    title = forms.CharField()

mynotes_site/notes/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, reverse, redirect

from .forms import NoteForm, SubtasksForm
from .models import Note, Subtasks


def all_notes(request: HttpRequest) -> HttpResponse:
    context = {
        'notes': Note.objects.all().prefetch_related('subtasks_set'),
    }
    return render(request, 'notes/all_notes.html', context=context)


def create_note(request: HttpRequest) -> HttpResponse:
    if request.POST:
        form = NoteForm(request.POST)
        if form.is_valid():
            Note.objects.create(**form.cleaned_data)
            url = reverse('notes:all_notes')
            return redirect(url)
    context = {
        'form': NoteForm(),
    }
    return render(request, 'notes/create_note.html', context=context)


def delete_notes(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        note_ids = request.POST.getlist('is_delete')
        Note.objects.filter(id__in=note_ids).delete()
        url = reverse('notes:all_notes')
        return redirect(url)
    context = {
        'notes': Note.objects.all(),
    }
    return render(request, 'notes/delete_notes.html', context=context)


def add_subtask(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        note_id = request.POST.get('is_selected')
        url = reverse('notes:add_subtask_for_id', args=(note_id,))
        return redirect(url)
    context = {
        'notes': Note.objects.all(),
    }
    return render(request, 'notes/add_subtask.html', context=context)


def add_subtask_for_id(request: HttpRequest, note_id: int) -> HttpResponse:
    note = Note.objects.get(id=note_id)
    if request.method == 'POST':
        form = SubtasksForm(request.POST)
        if form.is_valid():
            Subtasks.objects.create(title=form.cleaned_data['title'], note=note)
            url = reverse('notes:all_notes')
            return redirect(url)
    context = {
        'note': note,
        'note_id': note_id,
        'form': SubtasksForm(),
    }
    return render(request, 'notes/add_subtask_for_id.html', context=context)

mynotes_site/notes/templates/notes/add_subtask.html
{% extends 'notes/base.html' %}

{% block title %}
    ADD SUBS
{% endblock %}

{% block body %}
    <h1>Add subtask:</h1>
    <p>
    <form method="post">
        {% csrf_token %}
        <ul>
            {% for note in notes %}
                <li>
                    <input type="checkbox" name="is_selected" value="{{ note.id }}" class="form-check-input">
                    {{ note.title }}
                </li>
            {% endfor %}
        </ul>
        <button type="submit" class="btn btn-primary">
            add
        </button>
    </form>
    </p>
    <p>
    <form action="{% url 'notes:all_notes' %}">
        <button type="submit" class="btn btn-secondary">
            Back to main
        </button>
    </form>
    </p>
{% endblock %}

mynotes_site/notes/templates/notes/add_subtask_for_id.html
{% extends 'notes/base.html' %}

{% block title %}
    Add subtask
{% endblock %}

{% block body %}
    <h1>Add subtask for note(id={{ note_id }})</h1>
    <p>
    <form method="post">
        {% csrf_token %}
        <p>
            <label for="title" class="form-label">Title</label>
            <input type="text" id="title" class="form-control">
        </p>
        <button type="submit" class="btn btn-primary">
            add
        </button>
    </form>
    </p>
    <p>
    <form action="{% url 'notes:add_subtask' %}">
        <button type="submit" class="btn btn-warning">
            Back to previous page
        </button>
    </form>
    </p>
    <p>
    <form action="{% url 'notes:all_notes' %}">
        <button type="submit" class="btn btn-secondary">
            Back to main page
        </button>
    </form>
    </p>
{% endblock %}

mynotes_site/notes/templates/notes/all_notes.html
{% extends 'notes/base.html' %}

{% block title %}
    All Notes
{% endblock %}

{% block body %}
    <h1>All notes:</h1>
    <p>
    <ul>
        {% for note in notes %}
            {% if note.subtasks_set.all %}
                <li>
                    {{ note.title }}
                    <ul>
                        {% for subtask in note.subtasks_set.all %}
                            <li>{{ subtask.title }}</li>
                        {% endfor %}
                    </ul>
                </li>
            {% else %}
                <li>{{ note.title }}</li>
            {% endif %}
        {% endfor %}
    </ul>
    </p>
    <p>
    <form action="{% url 'notes:create_note' %}">
        <button type="submit" class="btn btn-success">Create a new one</button>
    </form>
    </p>
    <p>
    <form action="{% url 'notes:delete_selected' %}">
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
    </p>
    </p>
    <p>
    <form action="{% url 'notes:add_subtask' %}">
        <button type="submit" class="btn btn-info">add sub</button>
    </form>
    </p>
{% endblock %}

mynotes_site/notes/templates/notes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
{% block body %}
    Base Body
{% endblock %}
</body>
</html>

mynotes_site/notes/templates/notes/create_note.html
{% extends 'notes/base.html' %}

{% block title %}
    Create Note
{% endblock %}

{% block body %}
    <h1>Create note</h1>
    <p>
    <form method="post">
        {% csrf_token %}
        <p>
            <label for="title" class="form-label">Title</label>
            <input type="text" id="title" class="form-control" name="title">
        </p>
        <button type="submit" class="btn btn-success">
            Create
        </button>
    </form>
    </p>
    <p>
    <form action="{% url 'notes:all_notes' %}">
        <button type="submit" class="btn btn-secondary">
            Back to notes
        </button>
    </form>
    </p>
{% endblock %}

mynotes_site/notes/templates/notes/delete_notes.html
{% extends 'notes/base.html' %}

{% block title %}
    Delete Notes
{% endblock %}

{% block body %}
    <h1>Delete notes:</h1>
    <p>
    <form method="post">
        {% csrf_token %}
        <ul>
            {% for note in notes %}

                <li>
                    <input type="checkbox" name="is_delete" value="{{ note.id }}" class="form-check-input">
                    {{ note.title }}
                </li>
            {% endfor %}
        </ul>
        <button type="submit" class="btn btn-danger">DELETE</button>
    </form>
    </p>
    <p>
    <form action="{% url 'notes:all_notes' %}">
        <button type="submit" class="btn btn-secondary">
            Back to notes
        </button>
    </form>
    </p>
{% endblock %}